---
#HTTPD
vhosts_configs: /etc/httpd/conf.d/

#MariaDB 
mariadb_repo: http://yum.mariadb.org/10.4/centos7-amd64
mariadb_gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB

mariadb_packages:
  - MariaDB-server
  - MariaDB-client
  - MySQL-python

mariadb_service: mariadb

mariadb_user: default_bitrix
mariadb_user_pass: default_bitrix
mariadb_db: default_bitrix

#Nginx
nginx_sites: /etc/nginx/bx/site_enabled/

#PHP
php_version: 73
php_fpm_service: "php{{ php_version }}-php-fpm"

php_packages:
  - php{{ php_version }}-php-fpm
  - php{{ php_version }}-php-common
  - php{{ php_version }}-php-gd
  - php{{ php_version }}-php-gmp
  - php{{ php_version }}-php-json
  - php{{ php_version }}-php-intl
  - php{{ php_version }}-php-mbstring
  - php{{ php_version }}-php-mysqlnd
  - php{{ php_version }}-php-cli
  - php{{ php_version }}-php-recode
  - php{{ php_version }}-php-tidy
  - php{{ php_version }}-php-xml
  - php{{ php_version }}-php-xmlrpc
  - php{{ php_version }}-php-pecl-zip
  - php{{ php_version }}-php-opcache
  - php{{ php_version }}-php-pecl-imagick
  - php{{ php_version }}-php-ldap

#Additional software

additional_packages:
  - catdoc
  - xls2csv
  - mc
