apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    role: monitor
    tier: backend
  namespace: grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana
    role: monitor
    tier: backend