---
- name: Create destination directory
  file:
    dest: /var/www/{{ domain }}
    state: directory
    owner: apache
    group: apache
    mode: 0770
- name: Copy bitrixsetup files
  copy:
    src: files/bitrixsetup/
    dest: /var/www/{{ domain }}/
    owner: apache
    group: apache
    mode: '0760'
- name: Copy config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  with_items:
    - { src: 'templates/nginx_template.conf.j2', dest: "/etc/nginx/bx/site_enabled/{{ domain }}.conf" }
    - { src: 'templates/httpd_template.conf.j2', dest: "/etc/httpd/bx/conf/{{ domain }}.conf" }
  notify:
    - httpd reload
    - nginx reload
- name: Create MySQL user with name "{{ db_user }}" and password {{ db_user_pass }} with all privileges on "{{ db_name }}"
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_user_pass }}"
    priv: "{{ db_name }}.*:ALL"
    host: localhost
    state: present
- name: Create the database with name "{{ db_name }}"
  mysql_db:
    name: "{{ db_name }}"
    state: present
- name: Editing .settings.php and dbconn.php
  replace:
    path: "{{ item.dest }}"
    regexp: "{{ item.reg }}"
    replace: "{{ item.rep }}"
  with_items:
    - { dest: "/var/www/{{ domain }}/bitrix/.settings.php", reg: '__DATABASE__', rep: "{{ db_name }}" }
    - { dest: "/var/www/{{ domain }}/bitrix/.settings.php", reg: '__LOGIN__', rep: "{{ db_user }}" }
    - { dest: "/var/www/{{ domain }}/bitrix/.settings.php", reg: '__PASSWORD__', rep: "{{ db_user_pass }}" }
    - { dest: "/var/www/{{ domain }}/bitrix/php_interface/dbconn.php", reg: '__DATABASE__', rep: "{{ db_name }}" }
    - { dest: "/var/www/{{ domain }}/bitrix/php_interface/dbconn.php", reg: '__LOGIN__', rep: "{{ db_user }}" }
    - { dest: "/var/www/{{ domain }}/bitrix/php_interface/dbconn.php", reg: '__PASSWORD__', rep: "{{ db_user_pass }}" }

